In [3]:
import torch
from torch.distributions import multinomial
from d2l import torch as d2l

In [10]:
fair_probs = torch.ones([6]) / 6
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 0., 1., 0., 0., 0.])

In [14]:
multinomial.Multinomial(10, fair_probs).sample()

tensor([0., 2., 3., 3., 2., 0.])

In [15]:
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000

tensor([0.1790, 0.1760, 0.1630, 0.1710, 0.1360, 0.1750])

In [18]:
counts = multinomial.Multinomial(10, fair_probs).sample((500,))
cum_counts = counts.cumsum(dim = 0)
estimates = cum_counts / cum_counts.cum(dim = 1, keepdims=True)

d2l.set_figsize((6, 4.5))
for i in range(6):
    d2l.plt.plot(estimates[:, i].numpy(),
                label=("P(die=" + str(i + 1)))